intoduce module host init
epiphany-platform/e-structures pull request #14
Opened 2021-03-08 16:43 UTC by mkyc

2021-03-08 16:56 UTC, mkyc commented
This also introduces workaround for #10 issue

2021-03-09 08:17 UTC, erzetpe requested changes

2021-03-09 08:17 UTC, erzetpe commented on utils/load/load.go
> +		err = state.UnmarshalDoNotUse(bytes)
What??

2021-03-09 08:17 UTC, erzetpe commented on utils/load/load.go
> +		// TODO end of temporary code
I think that this is a really bad practice to do such things.

2021-03-09 08:17 UTC, erzetpe commented on state/v0/state_v0.go
> +// DO NOT USE!!!
It looks really weird.

2021-03-09 11:58 UTC, mkyc commented on utils/load/load.go
> +		err = state.UnmarshalDoNotUse(bytes)
Ok, so here goes my explanation for this ugly code: 

There is an issue #10 that influences cooperation between modules. Currently if you ie.: init-plan-apply AzBI module, it will also create following piece of code in `state.json` file: 

```json
"azks": {
     "status": "",
     "config": null,
     "output": null
  },
```

That is incorrectly initialised empty configuration part and most problematic is empty `status` field because it influences new e-structures validation and prevents from loading state file due to this empty `status` field. 

To solve this issue I made three things in this PR:
 * I created `load` and `save` packages with functions to load and save configurations and state. This will make management on those operations centralised in e-structures. 
 * I added validation also to Marshal methods to be performed before save. This will prevent saving invalid config or state. 
 * I added this workaround code to handle current situation. To do so, I needed to separate Unmarshal method into two separate steps: load struct and validate it. This is just workaround for and I made comment in every possible place not to start using it in another places.

2021-03-09 11:59 UTC, mkyc commented on utils/load/load.go
> +		// TODO end of temporary code
yeah, I'm aware of this, but I wanted to make it as visible as possible.

2021-03-09 11:59 UTC, mkyc commented on state/v0/state_v0.go
> +// DO NOT USE!!!
And that is exactly how I wanted it to look :) This has to be visible in every possible way.

2021-03-09 12:02 UTC, erzetpe approved these changes
It's still ugly as hell. Please fix issue and replace this code with something that we can consider as production ready code. :)

2021-03-09 12:11 UTC, mkyc commented
> It's still ugly as hell. Please fix issue and replace this code with something that we can consider as production ready code. :)

I will do it as soon as possible.

2021-03-09 14:11 UTC, merged