Add AzKS
epiphany-platform/e-structures pull request #5
Opened 2021-01-20 14:34 UTC by mkyc

2021-02-01 14:35 UTC, erzetpe requested changes

2021-02-01 14:35 UTC, erzetpe commented on azks/v0/azks_v0_test.go
> +package v0
This test is extremely hard to read. Please change this into more readable and shorter form.

2021-02-01 14:55 UTC, seriva commented
I think we discussed this already but maybe there is a better way todo this validation? JSON schema or something?

2021-02-01 16:13 UTC, mkyc commented on azks/v0/azks_v0_test.go
> +package v0
Can you propose any? There is 33 values stored in 5 structures. Some of them are lists. Tests are checking mostly errors for each possible missing value in input json. I do not see how I can make it shorter. Whatever way we choose there is need to provide those ~60 json, and we would have around the same amount of lines.

2021-02-01 16:15 UTC, mkyc commented on azks/v0/azks_v0.go
> +	constraint, err := semver.NewConstraint(fmt.Sprintf("~%d", v.Major()))
Hmmm ... no. It's perfectly fine.

2021-02-01 16:21 UTC, mkyc commented
> I think we discussed this already but maybe there is a better way todo this validation? JSON schema or something?

Yes, there is issue #3 but I didn't want to introduce it in this PR, as it is big enough already. I did reviewed some of available options and decided that I want to do it separately. But issue #3 is even in this sprint so I consider starting it very soon.

2021-02-01 16:30 UTC, erzetpe commented on azks/v0/azks_v0_test.go
> +package v0
Maybe it's  a better not to use table tests in this place? Or split validators and test JSON in chunks with smaller tests? I have no idea at this moment, but this is very huge file and changing this if needed will be very hard later on to maintain.

2021-02-01 16:32 UTC, erzetpe commented on azks/v0/azks_v0.go
> +	constraint, err := semver.NewConstraint(fmt.Sprintf("~%d", v.Major()))
So this can stay, but I like more verbose style. I can accept this.

2021-02-01 16:33 UTC, mkyc commented on azks/v0/azks_v0_test.go
> +package v0
Ok, I'll think about some way to divide it maybe into smaller subsets.

2021-02-01 20:29 UTC, atsikham requested changes

2021-02-01 20:29 UTC, atsikham commented on azbi/v0/azbi_v0.go
> +				}
WDYT about adding "break" here to reduce loop iterations?

2021-02-01 20:29 UTC, atsikham commented on azks/v0/azks_v0_test.go
> +package v0
I don't agree that it's hard to fix/read as this file is structured and when you run tests, IDE shows where exactly the problem is, but agree that probably it could be splitted. May be we even could have a standard full yaml configuration, than we can use some function(s) to remove/update fields there and use in tests - such way we could achieve config duplications.

2021-02-02 09:04 UTC, seriva commented on azks/v0/azks_v0_test.go
> +package v0
Yeah I agree with @atsikham that in an IDE its not really a problem. However it would be good if this would be broken down into smaller pieces.

2021-02-02 12:59 UTC, mkyc commented on azks/v0/azks_v0_test.go
> +package v0
I just pushed version with tests separated into smaller pieces.

2021-02-02 12:59 UTC, mkyc commented on azbi/v0/azbi_v0.go
> +				}
Added along with unit test for this method. Good spot!

2021-02-02 13:33 UTC, atsikham approved these changes

2021-02-02 14:43 UTC, seriva approved these changes

2021-02-02 15:04 UTC, merged